import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "Adolfo Leon' Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body >{children}</body>
    </html>
  );
}
